### ISSUE TITLE
Two duplicate packages uploaded for linux-64

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-assertive.datetimes-feedstock#5]
After PR #4 was merged, the CircleCI build uploaded two tarbals for linux-64/r-assertive.datetimes-0.0_2-r341_1.tar.bz2:

![screenshot from 2018-06-24 15-58-32](https://user-images.githubusercontent.com/1608317/41823109-076da21e-77c8-11e8-9c0c-b5904c582a04.png)

https://anaconda.org/conda-forge/r-assertive.datetimes/files

This is causing the [CircleCI build](https://circleci.com/gh/conda-forge/r-assertive-feedstock/11?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for my PR to fix r-assertive (https://github.com/conda-forge/r-assertive-feedstock/pull/4) to break due to a mismatch in the r-assertive.datetimes tarball.

```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/linux-64/r-assertive.datetimes-0.0_2-r341_1.tar.bz2'.
  download saved to: /opt/conda/pkgs/r-assertive.datetimes-0.0_2-r341_1.tar.bz2
  expected md5 sum: 68735625c682bbc72ab9361ca298f44c
  actual md5 sum: 3651d120a2b58bf18c398b5c92996c5f
```

**Comment by bgruening** [comment]
This is concerning :(
I marked on of the packages as broken.

**Comment by jdblischak** [comment]
> This is concerning :(

Unfortunately it's always something. 

> I marked on of the packages as broken.

Thanks! That seems to have fixed it.
